### PR TITLE
Changed nativeExe from File to Option[File]

### PR DESCRIPTION
**Pull request by paulmdavies**
@d40cht Can you have a look at this, please, Alex? Seems like a sensible change, even though it'll break backwards compatibility. If you'd prefer that wasn't the case, and have a solution, let me know and I'll happily implement.

### CODE REVIEW

**Comment by d40cht** [comment]
Happy to consider it. Could you let me know the rationale though? AFAICR, the nativeExe key is only in use when you're building native executables. So I can't at the moment imagine why it would ever be None.

Also - could you get the tests running in the pull request? Travis says no at the moment.

**Comment by paulmdavies** [comment]
I can't really see why it would ever be None either, but the default value is file( "" ), which is a bit nasty, so None as a default seems better.

I'm looking into Travis, but I can't run the tests on my machine - it complains of a lack of boost/python.hpp. Any ideas how to fix that? Sounds like a problem with my machine config, but surely the tests should be machine independent?

**Comment by d40cht** [comment]
The tests should be machine independent to some degree. I was trying
building python modules as part of the process (it all needs some tidying,
but also access to a variety of OS setups - which I don't have), so you
should install the appropriate packages. There's a set of apt calls here:

https://github.com/d40cht/sbt-cpp/blob/master/.travis.yml

Which should show you what's needed.

file("") is a bit nasty. That sounds like a reasonable justification -
although I'm questioning why the key needs a default value at all. Can you
remove that default and only allow it to be set in targets that build
executables?

**Comment by paulmdavies** [comment]
You probably understand this stuff better than me - what are the implications of having a key with no default? The user isn't required to override it, are they? Presumably will it just throw some (probably incomprehensible) error if you try to use it when it isn't set? Is that desirable behaviour? I'm not sure...

**Comment by d40cht** [comment]
You will get an error message only if you ask for that key to be
evaluated,. So if you ask for a nativeExe for a library target it'll
complain. But not if you ask for it for an executable target where it will
build as expected.

**Pull request closed without merging**
